client-config:
  TimeoutMs: 3000                              # uint64                   // timeout for requesting Nacos server, default value is 10000ms
  ListenInterval: 0                         # uint64                   // Deprecated
  BeatInterval: 0                           # int64                    // the time interval for sending beat to server,default value is 5000ms
  NamespaceId: "e12caeed-f6e0-4376-a052-ce7693a492ba"                   # string                   // the namespaceId of Nacos.When namespace is public, fill in the blank string here.
  AppName: ""                               # string                   // the appName
  AppKey": ""                               # string                   // the client identity information
  Endpoint: ""                              # string                   // the endpoint for get Nacos server addresses
  RegionId: ""                              # string                   // the regionId for kms
  AccessKey: ""                             # string                   // the AccessKey for kms
  SecretKey: ""                             # string                   // the SecretKey for kms
  OpenKMS: false                            # bool                     // it's to open kms,default is false. https://help.aliyun.com/product/28933.html
  CacheDir: ""                              # string                   // the directory for persist nacos service info,default value is current path
  DisableUseSnapShot: false                 # bool                     // It's a switch, default is false, means that when get remote config fail, use local cache file instead
  UpdateThreadNum: 0                        # int                      // the number of goroutine for update nacos service info,default value is 20
  NotLoadCacheAtStart: true                # bool                     // not to load persistent nacos service info in CacheDir at start time
  UpdateCacheWhenEmpty: false               # bool                     // update cache when get empty service instance from server
  Username: ""                              # string                   // the username for nacos auth
  Password: ""                              # string                   // the password for nacos auth
  LogDir: ""                                # string                   // the directory for log, default is current path
  LogLevel: "debug"                              # string                   // the level of log, it's must be debug,info,warn,error, default value is info
  ContextPath: ""                           # string                   // the nacos server contextpath
  AppendToStdoutL: false                    # bool                     // if append log to stdout

server-config:
   - Scheme: ""                               #string   // the nacos server scheme,default=http,this is not required in 2.0
     ContextPath: ""                          #string   // the nacos server contextpath,default=/nacos,this is not required in
     IpAddr: "150.158.46.17"                               #string   // the nacos server address
     Port: 8848                                  #uint64   // nacos server port
     GrpcPort: 0                              #uint64   // nacos server grpc port, default=server port + 1000, this is not required
#   - Scheme: ""                               #string   // the nacos server scheme,default=http,this is not required in 2.0
#     ContextPath: ""                          #string   // the nacos server contextpath,default=/nacos,this is not required in
#     IpAddr: "150.158.46.17"                               #string   // the nacos server address
#     Port: 88490                                  #uint64   // nacos server port
#     GrpcPort: 0                              #uint64   // nacos server grpc port, default=server port + 1000, this is not required
